"""deleted attributes

Revision ID: e977eb42a103
Revises: b106f0d4ae01
Create Date: 2025-01-17 10:20:20.623062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e977eb42a103'
down_revision = 'b106f0d4ae01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('age')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('age', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
